resource "local_file" "pets" {
  filename = var.filename
  content = var.content
}

resource "random_pet" "my-pet" {
  prefix = var.prefix
  separator = var.separator
  length = var.length
}

# We can get the reference expression "id" given by the random_pet resource as an output
# for that we would need to use the output block
output "pet-name" {
  value = random_pet.my-pet
  # the description is optional
  description = "Record the value of pet ID generated by the random_pet resource"
}
